### ISSUE TITLE
Definition conflicts with previous value (iOS)

### ISSUE THREAD

**Issue by HeroSony** [livekit/client-sdk-ios#6] opened 2021-09-25 10:40 UTC
Hello, I encounter a problem after install LiveKit and running the app.

```
Xcode Version 12.3 (12C33)
LiveKit main branch
```
<img width="1515" alt="Screen Shot 2021-09-25 at 5 31 27 PM" src="https://user-images.githubusercontent.com/4160246/134768554-5d613546-91a7-465a-800b-f92e0e59c413.png">

**Comment by hiroshihorie** [comment] 2021-09-25 11:45
Hi @HeroSony ! I will check it out in a few hours. 😁

**Comment by hiroshihorie** [comment] 2021-09-25 14:35
@HeroSony I confirmed it compiles with Xcode Version **12.5.1 (12E507)**, so Swift ver should be **5.4.2**.
Maybe this is due to some changes in Swift but I'm not sure yet. Xcode 13 is available now, can you try updating ?
Can you try if the test app compiles https://github.com/livekit/ios-test-apps ?

**Comment by HeroSony** [comment] 2021-09-25 15:04
@hiroshihorie I shall update Xcode to the latest and try compiling again. Letting you know afterward. Thanks for your confirmation.

**Comment by hiroshihorie** [comment] 2021-10-05 21:23
Hi @HeroSony would like to hear if it worked out 😁

**Comment by Zharas0904** [comment] 2021-11-24 06:01
Hi @hiroshihorie, Is there any updates? have the same issue on **Xcode Version 12.4 (12D4e)**

**Comment by hiroshihorie** [comment] 2021-11-24 06:41
@Zharas0904 Hi, may i know which issue exactly, "Definition conflicts with previous...." ?

**Comment by Zharas0904** [comment] 2021-11-24 08:53
Hi @hiroshihorie, yeap, exactly the same issue "Definition conflicts with previous value", with value name selectedDimension

**Comment by hiroshihorie** [comment] 2021-11-24 10:27
Hi @Zharas0904 I will look into this today. I might need to get lower versions of Xcode to reproduce this error.

**Comment by Zharas0904** [comment] 2021-11-25 11:10
Hi @hiroshihorie, how you doing? is there any updates? Did you solve this issue?

**Comment by hiroshihorie** [comment] 2021-11-25 14:23
Hi @Zharas0904 , I'm struggling to reproduce it. But I did release a new v0.9.0. Could you try if that works ?

**Comment by Zharas0904** [comment] 2021-11-26 04:49
Hi @hiroshihorie, yeah, sure we are using **Xcode Version 12.4 (12D4e)**  and **Swift 5**

**Comment by hiroshihorie** [comment] 2021-11-26 06:57
Ok thanks for the detailed feedback will dig into it now

**Comment by hiroshihorie** [comment] 2021-11-26 23:47
Hello can you try v0.9.1

**Comment by Zharas0904** [comment] 2021-11-30 09:43
Hi @hiroshihorie, sorry for late reply, compiling on Xcode 12.4 works fine, thanks for the prompt solution of the problem!)

... but we found new issue:
Previously we've started implementing LiveKit delegate methods, all methods called/worked fine on package version v0.8.2 and we received all call related events, but after updating package version to v0.9.2 we are not getting any events (except didConnect)
Could you, please, check your last updates? maybe you missed something or forgot to change dependency versions?

**Comment by hiroshihorie** [comment] 2021-11-30 10:07
Hi @Zharas0904 , I will take a look but
It sounds like your object is getting deallocated. Can you make sure your object has strong reference somewhere, since Room.add(delegate:) keeps **weak reference** only.

**Comment by davidzhao** [comment] 2021-11-30 17:13
closing this issue as the original problem has been resolved. @Zharas0904 please find us on slack if there are other issues that you need help with.

**Closed by davidzhao** 2021-11-30 17:13 UTC
